"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { parseCourseCSV, type CourseParseResult } from "@/lib/utils/course-csv-parser";
import { Loader2, CheckCircle2, AlertTriangle, Info, FileSpreadsheet, Sparkles, Check } from "lucide-react";
import { cn } from "@/lib/utils";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

const AI_PROMPT = `Act as an expert course curriculum designer. I have a SINGLE long YouTube video URL (One-Shot Course): [INSERT URL HERE].

**YOUR GOAL:**
Analyze the video content/chapters and generate a CSV where **each lesson plays a specific segment** of this video.

**CRITICAL INSTRUCTION - VIDEO URLS:**
You **MUST** calculate both the **start** and **end** times in **seconds** for each chapter.
- Use the standard query format: \`start=SECONDS&end=SECONDS\`
- If the URL contains \`?\`, append \`&start=...&end=...\`.
- If the URL does NOT contain \`?\`, append \`?start=...&end=...\`.

**REDUNANCY PREVENTION:**
- **Leave the 'Image URL' column EMPTY** for individual lessons/chapters. The video player already provides a thumbnail, so adding another one is redundant.

**Examples:**
- Segment **02:30 to 05:00** (150s to 300s) -> \`https://www.youtube.com/watch?v=xyz&start=150&end=300\`
- Segment **10:00 to 12:45** (600s to 765s) -> \`https://youtu.be/xyz?start=600&end=765\`

**Structure & Format:**
1. **Modules**: Use the main topic.
2. **Chapters/Lessons**: Break down the video by its distinct topics.
3. **Format**: Standard CSV, Headers, Double Quotes \`"\` around text.
4. **No conversational preamble**.

**Columns:**
"Module Title","Chapter Title","Lesson Title","Content Type","Video URL","Image URL","Description"

**Example Output:**
\`\`\`csv
"Full Course","Introduction","Welcome","Video","https://youtube.com/watch?v=123&start=0&end=300","","Intro"
"Full Course","Part 1","Setup","Video","https://youtube.com/watch?v=123&start=300&end=900","","Environment setup"
\`\`\``;

interface CourseCSVImportDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onImport: (data: CourseParseResult) => void;
}

export function CourseCSVImportDialog({
    open,
    onOpenChange,
    onImport,
}: CourseCSVImportDialogProps) {
    const [csvText, setCsvText] = useState("");
    const [parseResult, setParseResult] = useState<CourseParseResult | null>(null);
    const [isPromptCopied, setIsPromptCopied] = useState(false);

    const handleCopyPrompt = () => {
        navigator.clipboard.writeText(AI_PROMPT);
        setIsPromptCopied(true);
        setTimeout(() => setIsPromptCopied(false), 2000);
    };

    const handleParse = () => {
        if (!csvText.trim()) {
            setParseResult({
                success: false,
                modules: [],
                errors: ["Please paste CSV text"],
                warnings: [],
            });
            return;
        }

        const result = parseCourseCSV(csvText);
        setParseResult(result);
    };

    const handleImport = () => {
        if (!parseResult || !parseResult.success) return;

        onImport(parseResult);
        // Reset and close
        setCsvText("");
        setParseResult(null);
        onOpenChange(false);
    };

    const handleClose = () => {
        setCsvText("");
        setParseResult(null);
        onOpenChange(false);
    };

    return (
        <Dialog open={open} onOpenChange={handleClose}>
            <DialogContent className="max-w-4xl max-h-[90vh] flex flex-col">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <FileSpreadsheet className="h-5 w-5 text-green-600" />
                        Import Course Content from CSV
                    </DialogTitle>
                    <DialogDescription>
                        Paste the CSV text generated by AI to bulk create modules, chapters, and lessons.
                    </DialogDescription>
                </DialogHeader>

                <div className="flex-1 space-y-4 overflow-y-auto pr-2">
                    <Alert>
                        <Info className="h-4 w-4" />
                        <AlertDescription className="w-full">
                            <div className="flex items-start justify-between gap-4">
                                <div className="space-y-1 text-sm">
                                    <p className="font-semibold">How to use:</p>
                                    <ol className="list-decimal ml-4 space-y-1 text-muted-foreground">
                                        <li>Copy the <strong>AI Prompt</strong> below.</li>
                                        <li>Paste it into ChatGPT/Claude along with your YouTube Playlist URL.</li>
                                        <li>Copy the CSV output and paste it here.</li>
                                    </ol>
                                </div>
                                <Button
                                    size="sm"
                                    variant="outline"
                                    className={cn(
                                        "gap-2 transition-all duration-300 whitespace-nowrap",
                                        isPromptCopied ? "border-green-500 text-green-600 bg-green-50" : "border-primary/20 hover:border-primary/50"
                                    )}
                                    onClick={handleCopyPrompt}
                                >
                                    {isPromptCopied ? (
                                        <>
                                            <Check className="h-4 w-4" />
                                            Copied!
                                        </>
                                    ) : (
                                        <>
                                            <Sparkles className="h-4 w-4 text-amber-500" />
                                            Copy AI Prompt
                                        </>
                                    )}
                                </Button>
                            </div>
                        </AlertDescription>
                    </Alert>

                    <div className="space-y-2">
                        <label className="text-sm font-bold">CSV Content</label>
                        <Textarea
                            placeholder={`Module Title,Chapter Title,Lesson Title,Content Type,Video URL,Image URL\n"Basics","Intro","Welcome","Video","...", "..."`}
                            value={csvText}
                            onChange={(e) => {
                                setCsvText(e.target.value);
                                if (parseResult) setParseResult(null);
                            }}
                            className="font-mono text-xs min-h-[150px] bg-slate-50 border-2"
                        />
                    </div>

                    {!parseResult && csvText && (
                        <Button onClick={handleParse} variant="secondary" className="w-full">
                            Validate Structure
                        </Button>
                    )}

                    {parseResult && (
                        <div className="space-y-3 animate-in fade-in slide-in-from-top-2">
                            {parseResult.success && parseResult.modules.length > 0 && (
                                <div className="space-y-2 border rounded-md p-4 bg-green-50/20 border-green-200">
                                    <div className="flex items-center gap-2 text-green-800 font-semibold mb-2">
                                        <CheckCircle2 className="h-4 w-4" />
                                        <span>Identified: {parseResult.modules.length} Modules</span>
                                    </div>

                                    <Accordion type="single" collapsible className="w-full">
                                        {parseResult.modules.map((mod, idx) => (
                                            <AccordionItem key={idx} value={`item-${idx}`}>
                                                <AccordionTrigger className="py-2 text-sm">
                                                    {mod.title} ({mod.chapters.length} chapters)
                                                </AccordionTrigger>
                                                <AccordionContent>
                                                    <div className="pl-4 space-y-2">
                                                        {mod.chapters.map((ch, cIdx) => (
                                                            <div key={cIdx} className="text-xs text-muted-foreground border-l-2 pl-2">
                                                                <p className="font-medium text-foreground">{ch.title}</p>
                                                                <div className="flex flex-wrap gap-1 mt-1">
                                                                    {ch.lessons.map((l, lIdx) => (
                                                                        <Badge key={lIdx} variant="secondary" className="text-[10px]">
                                                                            {l.title}
                                                                        </Badge>
                                                                    ))}
                                                                </div>
                                                            </div>
                                                        ))}
                                                    </div>
                                                </AccordionContent>
                                            </AccordionItem>
                                        ))}
                                    </Accordion>
                                </div>
                            )}

                            {parseResult.errors.length > 0 && (
                                <Alert variant="destructive">
                                    <AlertTriangle className="h-4 w-4" />
                                    <AlertDescription>
                                        <p className="font-bold mb-1">Errors:</p>
                                        <ul className="text-xs space-y-1 list-disc ml-4">
                                            {parseResult.errors.map((err, i) => <li key={i}>{err}</li>)}
                                        </ul>
                                    </AlertDescription>
                                </Alert>
                            )}
                        </div>
                    )}
                </div>

                <DialogFooter className="pt-4 border-t">
                    <Button variant="ghost" onClick={handleClose}>Cancel</Button>
                    <Button
                        onClick={handleImport}
                        className="bg-green-600 hover:bg-green-700 text-white"
                        disabled={!parseResult?.success || parseResult.modules.length === 0}
                    >
                        Import Content
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
