"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { parseCalendarCSV, type ParsedCalendarEvent } from "@/lib/utils/calendar-csv-parser";
import { Loader2, CheckCircle2, AlertTriangle, Info } from "lucide-react";
import { cn } from "@/lib/utils";

interface CalendarCSVImportDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onImport: (events: ParsedCalendarEvent[]) => Promise<void>;
}

export function CalendarCSVImportDialog({
    open,
    onOpenChange,
    onImport,
}: CalendarCSVImportDialogProps) {
    const [csvText, setCsvText] = useState("");
    const [isImporting, setIsImporting] = useState(false);
    const [parseResult, setParseResult] = useState<ReturnType<typeof parseCalendarCSV> | null>(null);

    const handleParse = () => {
        if (!csvText.trim()) {
            setParseResult({
                success: false,
                events: [],
                errors: ["Please paste CSV text"],
                warnings: [],
            });
            return;
        }

        const result = parseCalendarCSV(csvText);
        setParseResult(result);
    };

    const handleImport = async () => {
        if (!parseResult || !parseResult.success || parseResult.events.length === 0) {
            return;
        }

        setIsImporting(true);
        try {
            await onImport(parseResult.events);
            // Success - close dialog and reset
            setCsvText("");
            setParseResult(null);
            onOpenChange(false);
        } catch (error) {
            console.error("Import failed:", error);
        } finally {
            setIsImporting(false);
        }
    };

    const handleClose = () => {
        if (!isImporting) {
            setCsvText("");
            setParseResult(null);
            onOpenChange(false);
        }
    };

    // Auto-parse when text changes
    const handleTextChange = (value: string) => {
        setCsvText(value);
        // Clear previous parse result when editing
        if (parseResult) {
            setParseResult(null);
        }
    };

    return (
        <Dialog open={open} onOpenChange={handleClose}>
            <DialogContent className="max-w-3xl max-h-[90vh] flex flex-col">
                <DialogHeader>
                    <DialogTitle>Import Timetable Events</DialogTitle>
                    <DialogDescription>
                        Paste the CSV text generated by AI to bulk import events
                    </DialogDescription>
                </DialogHeader>

                <div className="flex-1 space-y-4 overflow-y-auto">
                    {/* Instructions */}
                    <Alert>
                        <Info className="h-4 w-4" />
                        <AlertDescription>
                            <div className="space-y-1 text-sm">
                                <p className="font-medium">Expected format:</p>
                                <code className="block bg-muted p-2 rounded text-xs overflow-x-auto">
                                    Title,Description,Start Time,End Time,Type,Color
                                </code>
                                <p className="text-muted-foreground">
                                    Paste the CSV text from your AI chatbot below
                                </p>
                            </div>
                        </AlertDescription>
                    </Alert>

                    {/* CSV Input */}
                    <div className="space-y-2">
                        <label className="text-sm font-medium">CSV Text</label>
                        <Textarea
                            placeholder="Paste your CSV text here..."
                            value={csvText}
                            onChange={(e) => handleTextChange(e.target.value)}
                            className="font-mono text-sm min-h-[200px]"
                            disabled={isImporting}
                        />
                    </div>

                    {/* Parse Button */}
                    {csvText && !parseResult && (
                        <Button onClick={handleParse} variant="outline" className="w-full">
                            Validate CSV
                        </Button>
                    )}

                    {/* Parse Results */}
                    {parseResult && (
                        <div className="space-y-3">
                            {/* Success Summary */}
                            {parseResult.success && parseResult.events.length > 0 && (
                                <Alert className="border-green-500 bg-green-50">
                                    <CheckCircle2 className="h-4 w-4 text-green-600" />
                                    <AlertDescription className="text-green-800">
                                        <strong>Ready to import {parseResult.events.length} events</strong>
                                        <div className="mt-2 text-sm space-y-1">
                                            {parseResult.events.slice(0, 3).map((event, idx) => (
                                                <div key={idx} className="truncate">
                                                    • {event.title}
                                                    {event.start && ` (${event.start.toLocaleDateString()} ${event.start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })})`}
                                                </div>
                                            ))}
                                            {parseResult.events.length > 3 && (
                                                <div className="text-muted-foreground">
                                                    + {parseResult.events.length - 3} more events...
                                                </div>
                                            )}
                                        </div>
                                    </AlertDescription>
                                </Alert>
                            )}

                            {/* Errors */}
                            {parseResult.errors.length > 0 && (
                                <Alert variant="destructive">
                                    <AlertTriangle className="h-4 w-4" />
                                    <AlertDescription>
                                        <strong>Errors found:</strong>
                                        <ul className="mt-2 space-y-1 text-sm">
                                            {parseResult.errors.map((error, idx) => (
                                                <li key={idx}>• {error}</li>
                                            ))}
                                        </ul>
                                    </AlertDescription>
                                </Alert>
                            )}

                            {/* Warnings */}
                            {parseResult.warnings.length > 0 && (
                                <Alert className="border-yellow-500 bg-yellow-50">
                                    <AlertTriangle className="h-4 w-4 text-yellow-600" />
                                    <AlertDescription className="text-yellow-800">
                                        <strong>Warnings:</strong>
                                        <ul className="mt-2 space-y-1 text-sm">
                                            {parseResult.warnings.slice(0, 5).map((warning, idx) => (
                                                <li key={idx}>• {warning}</li>
                                            ))}
                                            {parseResult.warnings.length > 5 && (
                                                <li className="text-muted-foreground">
                                                    + {parseResult.warnings.length - 5} more warnings...
                                                </li>
                                            )}
                                        </ul>
                                    </AlertDescription>
                                </Alert>
                            )}
                        </div>
                    )}
                </div>

                <DialogFooter>
                    <Button variant="outline" onClick={handleClose} disabled={isImporting}>
                        Cancel
                    </Button>
                    <Button
                        onClick={handleImport}
                        disabled={
                            !parseResult ||
                            !parseResult.success ||
                            parseResult.events.length === 0 ||
                            isImporting
                        }
                    >
                        {isImporting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        Import {parseResult?.events.length || 0} Events
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
